networks:
  goodfood:
    driver: bridge
services:
  users-db:
    container_name: users-db
    image: postgres
    restart: always
    env_file:
      - ./users/db/.env
    volumes:
      - './users/db/data:/var/lib/postgresql/data'
      - './users/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5432:5432'
    networks:
      - goodfood

  restaurants-db:
    container_name: restaurants-db
    image: postgres
    restart: always
    env_file:
      - ./restaurants/db/.env
    volumes:
      - './restaurants/db/data:/var/lib/postgresql/data'
      - './restaurants/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5433:5432'
    networks:
      - goodfood

  plats-db:
    container_name: plats-db
    image: postgres
    restart: always
    env_file:
      - ./plats/db/.env
    volumes:
      - './plats/db/data:/var/lib/postgresql/data'
      - './plats/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5434:5432'
    networks:
      - goodfood

  users-api:
    container_name: users-api
    image: 'node:17-alpine'
    env_file:
      - ./users/api/.env
    working_dir: /usr/src/app
    volumes:
      - './users/api:/usr/src/app'
    command: npm run dev
    ports:
      - '3001:3001'
    networks:
      - goodfood
    depends_on:
      - users-db
    expose:
      - 3001

  auth-api:
    container_name: auth-api
    image: 'node:17-alpine'
    env_file:
      - ./auth/api/.env
    working_dir: /usr/src/app
    volumes:
      - './auth/api:/usr/src/app'
    command: npm run dev
    ports:
      - '3002:3002'
    networks:
      - goodfood
    depends_on:
      - users-api
    expose:
      - 3002

  plats-api:
    container_name: plats-api
    image: 'node:17-alpine'
    env_file:
      - ./plats/api/.env
    working_dir: /usr/src/app
    volumes:
      - './plats/api:/usr/src/app'
    command: npm run dev
    ports:
      - '3004:3004'
    networks:
      - goodfood
    depends_on:
      - plats-db
    expose:
      - 3004

  restaurants-api:
    container_name: restaurants-api
    image: 'node:17-alpine'
    env_file:
      - ./restaurants/api/.env
    working_dir: /usr/src/app
    volumes:
      - './restaurants/api:/usr/src/app'
    command: npm run dev
    ports:
      - '3003:3003'
    networks:
      - goodfood
    depends_on:
      - restaurants-db
    expose:
      - 3003
